### ISSUE TITLE
Persist id() call parameters between sessions

### ISSUE THREAD

**Issue by vklimontovich** [jitsucom/eventnative#195]
### Problem

At the moment, `id()` call persist user properties only in the local window environment. It means that id() should be called each time page is rendered. Which is not very convenient application consists from few independent components (example - website and application)

### Solution

Once call is made, tracker should record arguments to cookies or/and localstorage. On each track() call tracker should check cookies and restore user id if possible

**Comment by mx14** [comment]
this cookie should belong to "path=/" because by default it belongs to current page and cookie is being sent from this path.

for example:
1. load the domain.com/uri1/ page and cookie belong to /uri1/ path
2. execute eventN.id(...) with correct user id
3. load another page domain.com/uri2/ and cookie do not sent to it
4. eventN.track knows nothing about user id from previous call of eventN.id(...)

I tried your beta branch to test this feature. thank you

**Comment by xtreding** [comment]
Hi @mx14! Thank you for your comment!
We've fixed and released it in [1.28.1](https://github.com/jitsucom/eventnative/releases/tag/v1.28.1)
